services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: tma_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./backend/db:/var/lib/mysql:delegated
    ports:
      - "3306:3306"